# https://vuepress.github.io/zh/guide/deployment.html#github-pages
name: deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build VuePress Site
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: git-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: git@github.com:ModyQyW/mp-scss.git
          destination-repo: git@gitee.com:ModyQyW/mp-scss.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}

      - name: Deploy to Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ModyQyW
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ModyQyW/mp-scss
          branch: git-pages
